### ISSUE TITLE
Convert all paths to be system-agnostic

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_htmlmaker#23]
Create a new "paths" branch for this repository
Checkout the bookmaker repository's "paths" branch
Update all paths to reference the defs in header.rb (see tmparchive.rb for examples)
Rewrite all command line arguments using ruby's methods (Dir or fileutils, as appropriate)

You may not be able to rewrite the saxon commands to use pure ruby. We might want to create a method in our header.rb classes for this, or something. Ok to leave as-is for now, if you can't get it to work.

**Comment by mattretzer** [comment]
As per discussion with Nellie, left java saxon calls in backticks so they are processed by parent OS.. however variable-ized all paths so should still be platform agnostic.
Tested, ok
