### ISSUE TITLE
Character styles are getting dropped

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_htmlmaker#4]
Character style spans appear to be dropped during the conversion to html. I've confirmed that this is not being caused by the strip-toc.xsl. It's happening either at the conversion to xml or the conversion to html. This issue will fix https://github.com/macmillanpublishers/bookmaker_epubmaker/issues/12

**Comment by nelliemckesson** [comment]
After some testing, it looks like this is occurring during the conversion from .doc to .xml, via the powershell script in https://github.com/macmillanpublishers/WordXML-to-HTML. @ericawarren can you look into this?

**Comment by nelliemckesson** [comment]
It looks like the character styles have been preserved in No Love Allowed. Not sure what's different (didn't do any investigating).

**Comment by ericawarren** [comment]
I tested with a different file and character styles were also dropped in the epub (but not the pdf). The epub html preserves the styles as classes, though:

`<p class="FMTextNo-Indentfmtx1"><span class="spanitaliccharactersital"> Fusce aliquet pede non pede. </span>Suspendisse dapibus lorem pellentesque magna. Integer nulla. Donec blandit feugiat ligula. Donec hendrerit, felis et imperdiet euismod, purus ipsum pretium metus, in lacinia nulla nisl eget sapien.</p>`
`<p class="FMTextfmtx"><span class="spanitaliccharactersital">Donec ut est in lectus consequat consequat. </span>Etiam eget dui. Aliquam erat volutpat. Sed at lorem in nunc porta tristique. Proin nec augue. Quisque aliquam tempor magna. Pellentesque habitant morbi tristique senectus et netus et malesu<span class="spanaccentcharactersacc">ada fames ac turpis eges</span>tas. <span class="spanbolditalbem">Nunc ac magna. </span><span class="spancarryquerycq">Maecenas odio dol</span>or, <span class="spancross-referencexref">vulputat</span>e vel<span class="spanhyperlinkurl">, auctor ac, a</span>ccu<span class="spankeyphrasekp">msan id, </span>feli<span class="spanmaterialtocometk">s. Pellen</span>tesque<span class="spanpreservecharacterspre"> cursus sa</span>gittis <span class="spansmallcapscharacterssc">felis.</span></p>`
`<p class="FMTextfmtx"><span class="spanboldfacecharactersbf">Pellentesque porttitor, velit lacinia egestas auctor,</span> diam er<span class="spansmcapitalscital">os tempus a</span>rcu, nec vulp<span class="spansubscriptcharacterssub">utate augue </span>magna vel risu<span class="spansuperscriptcharacterssup">s. Cras non mag</span>na vel ante <span class="spansymbolssym">adipiscing r</span>honcus<span class="spansymbolsboldsymb">. Vivamus a</span> mi. <span class="spansymbolsitalsymi">Morbi neque. </span>Aliquam erat volutpat. Integer ultrices lobortis eros. Pellentesque habitant morbi tristique senectus et netus et male<span class="spanboldfacecharactersbf">suada fames ac turpis egestas. Proin semper, ante vitae </span>sollicitudin posuere, metus quam iaculis nibh, vitae scelerisque nunc massa eget pede. Sed velit urna, interdum vel, <span class="spanunderscorecharactersus">ultricies vel, faucibus at, quam. Donec e</span>lit est, consectetuer eget, consequat quis, tempus quis, wisi.</p>`

**Comment by nelliemckesson** [comment]
Ok I think this was just a weird fluke. Resolving.
